/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#9129c0",
        "primary-fixed-dim": "#cc66fa",
        primary: "#de8fff",
        "surface-bright": "#1A1A1A",
        "surface-variant": "#121212",
        "secondary-fixed": "#26e6ff",
        "surface-dim": "#000000",
        "surface-container-lowest": "#000000",
        "tertiary-dim": "#e51245",
        "on-primary": "#4e006e",
        "on-tertiary-fixed-variant": "#79001f",
        "on-primary-fixed": "#000000",
        "primary-container": "#d67aff",
        "surface-container-high": "#121212",
        "on-primary-container": "#3d0056",
        "secondary-container": "#006875",
        "surface-container-highest": "#1A1A1A",
        "surface-tint": "#de8fff",
        outline: "#7a7286",
        "on-secondary-fixed": "#003a42",
        "surface-container": "#080808",
        "error-container": "#a70138",
        error: "#ff6e84",
        "primary-fixed": "#d67aff",
        "tertiary-fixed-dim": "#ff7984",
        background: "#000000",
        "on-background": "#FFFFFF",
        "on-secondary-fixed-variant": "#005964",
        "on-secondary": "#004d57",
        "outline-variant": "#4b4558",
        "inverse-on-surface": "#595265",
        "on-tertiary-fixed": "#39000a",
        "tertiary-container": "#fc2a53",
        surface: "#000000",
        "on-primary-fixed-variant": "#4b0069",
        secondary: "#00e3fd",
        tertiary: "#ff6f7c",
        "on-tertiary-container": "#000000",
        "on-surface-variant": "#FFFFFF",
        "inverse-surface": "#fef7ff",
        "surface-container-low": "#050505",
        "on-surface": "#FFFFFF",
        "secondary-dim": "#00d4ec",
        "secondary-fixed-dim": "#00d7f0",
        "on-tertiary": "#49000f",
        "primary-dim": "#d575ff",
        "tertiary-fixed": "#ff9197",
        "error-dim": "#d73357",
        "on-error": "#490013",
        "on-secondary-container": "#e8fbff",
        "on-error-container": "#ffb2b9",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      fontSize: {
        xs: "0.7rem",
        sm: "0.8rem",
        base: "0.9rem",
        lg: "1rem",
        xl: "1.15rem",
        "2xl": "1.35rem",
        "3xl": "1.75rem",
        "4xl": "2.25rem",
        "5xl": "2.75rem",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      backdropBlur: {
        xl: "24px",
      },
    },
  },
  plugins: [],
};
